name: lumide_typescript
description: "TypeScript and JavaScript extension for Lumide"
version: 1.0.0
homepage: https://lumide.dev
repository: https://github.com/SoFluffyOS/lumide_typescript

topics:
  - lumide-languages
  - lumide-plugin

executables:
  lumide_typescript: main

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lumide_api: 1.1.0

dev_dependencies:
  lints: ^6.0.0
